### PR TITLE
Various edits & ability to download youtubedl  automatically

### PR DESCRIPTION
**Pull request by wdlkmpx**

### CODE REVIEW

**Comment by ThomasTheSpaceFox** [comment]
these changes broke the program due to the script assuming youtube-dl was in a very specific place.

**Comment by wdlkmpx** [comment]
It's working fine here.

If youtube-dl is not found then the script downloads it to /usr/local/bin, but that directory is preceded by /usr/bin /usr/sbin and /bin and /sbin. 

Maybe /usr/bin is the correct place to download to...

I'll add an xterm window showing the download progress in audioYT2.sh

**Comment by ThomasTheSpaceFox** [comment]
i think i will keep GTKplayYT out of updating/downloadig/checking for youtube-dl. i have removed your changes manually.
sorry, no hard feelings i hope!

**Comment by wdlkmpx** [comment]
Hahaha how dare you! By the way the scripts don't have the executable flag set

**Comment by ThomasTheSpaceFox** [comment]
thanks for pointing that out. i will add instructions on making the scripts executable to the INSTRUCTIONS.txt file and the wiki.

**Pull request merged**
